# Generated by Django 4.2.6 on 2023-10-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuelxpress_drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuelxpress_gasstations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelXpressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FX_fuel_type', models.CharField(max_length=100)),
                ('FX_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FX_delivery_location', models.TextField()),
                ('FX_order_status', models.CharField(default='Pending', max_length=50)),
                ('FX_order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('FX_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelxpress_drivers.fuelxpressdriver')),
                ('FX_gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelxpress_gasstations.fuelxpressgasstation')),
                ('FX_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
